// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.771
package vehicleModel

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import ()

func CreateVehicleModelForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"/vehicle-model\" hx-target=\"#vehicle-list\" hx-swap=\"afterbegin\" class=\"mb-4\"><div class=\"row g-2\"><div class=\"col\"><input name=\"year\" type=\"number\" class=\"form-control\" placeholder=\"Year\" required></div><div class=\"col\"><input name=\"make\" type=\"text\" class=\"form-control\" placeholder=\"Make\" required></div><div class=\"col\"><input name=\"model\" type=\"text\" class=\"form-control\" placeholder=\"Model\" required></div><div class=\"col\"><input name=\"bodyStyle\" type=\"text\" class=\"form-control\" placeholder=\"Body Style\" required></div><div class=\"col-auto\"><button type=\"submit\" class=\"btn btn-success\">Add Vehicle</button></div></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
